name: CI/CD User Management Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: user-service
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v3

      - name: ☕ Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: 🧪 Run tests (BDD + TDD)
        run: mvn clean test

      - name: 📦 Package JAR with Spring Boot Plugin
        run: mvn package -DskipTests

      - name: 🐳 Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔐 Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🐳 Build Docker Image
        run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: 🚢 Push Docker Image to DockerHub
        run: docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
